### ISSUE TITLE
Feature Request: Add Faker integration for replacements

### ISSUE THREAD

**Issue by franziskahahn** [webfactory/slimdump#19]
The replacement with "x" is helpful but I think replacements with other characters - or even better: human readable values - is an often needed use case.

**What do you think about implementing at least some basic options?**

Just a (very quick and dirty) draft I created today:

```php
        if ($this->dump == Config::REPLACE) {
            $replacement = $this->config->attributes()->replacement;

            $faker = Faker\Factory::create('de_DE');

            if ($replacement == 'FAKER_IBAN') {
                return $faker->iban('DE');
            } else if ($replacement == 'FAKER_NAME') {
                return $faker->firstName() . ' ' . $faker->lastName();
            }

            return $replacement;
        }
```

And the config could look like this:
```xml
<column name="username" dump="replace" replacement="FAKER_NAME" />
```

**Comment by mpdude** [comment]
Thanks for your suggestion!

Indeed, I've been thinking about this because I saw that @josecanhelp has tried something similar at https://github.com/webfactory/slimdump/compare/master...josecanhelp:slimdump.

I'd be :+1: for such a change as indeed the results may be much better when it comes to readability, developer experience and also data privacy. 

Do you think you could come up with a PR that fits into the current configuration syntax and allows to choose from the various Faker providers or even hook up new/custom ones in a generic way?

As a side note: Personally, I haven't yet had the need for something like this. In fact, it turned out helpful a few times already that `slimdump` dump were "reproducible", that is, you could perform `diff`s between dumps and see only the changed lines. That might not be the case when Faker data comes into play, but that's just an option you don't have to use :)

**Comment by franziskahahn** [comment]
Here you go: https://github.com/webfactory/slimdump/pull/21
