### ISSUE TITLE
Feature Request: Limit the dump of a table to a max of {n} columns

### ISSUE THREAD

**Issue by stijink** [webfactory/slimdump#20]
Oftentimes in development it is interesting to have a subset of the production data to test certain features. If a company has very large amount of data it is often not an option to dump a whole table worth of data. Instead it would be interesting to a limited subset of data either from the beginning or the end of a table (ORDER BY PK {ASC|DESC}, LIMIT n)

**Comment by franziskahahn** [comment]
If the data doesn't need to be consistent, ORDER BY RAND() might be a good option too (and because slimdump currently supports MySQL only).

If you need consistent data (my next hackday project) you could write a small script/command which writes a config.xml for you containing a specification for every table.

Just an example - export all things necessary to test one blog author
```xml
<?xml version="1.0" ?>
<slimdump>
    <table name="blog_user" dump="full" keep-auto-increment="false" condition="user_id = `{{FILL BY SCRIPT}}`">
        <column name="password" dump="masked" />
        <column name="username" dump="replace" replacement="FAKER_NAME" />
    </table>
    <table name="blog_article" dump="full" keep-auto-increment="false" condition="user_id = `{{FILL BY SCRIPT}}`" />
# ... and so on
</slimdump>

```
But I think this :top: is too specific to implement for all users of slimdump. Just my two cents :)

**Comment by MalteWunsch** [comment]
@stijink Maybe the condition attribute of the table element already satisfies your needs? A blunt version of the suggestion by @franziskahahn:

```xml
<table name="user" dump="full" condition="`id` <= 1000" />
```

or

```xml
<table name="user" dump="full" condition="`id` MOD 10 = 0" />
```

To maintain referential integrity, I use to adapt the condition:

```xml
<table name="messages" dump="full" condition="`sender_id` MOD 10 = 0 AND `receiver_id` MOD 10 = 0" />
```

Of course, depending in your data, this probably won't give you exactly 1000 users or 10% of them. For my use cases, this approximation has been good enough so far - do you need an exact number of (sorted) rows?

**Comment by stijink** [comment]
@MalteWunsch Good point, Thx 👍
